version: "3.8"
services:
  miservicio_mysql:
    image: mysql:8.0
    container_name: miservicio_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    deploy:
      restart_policy:
        condition: on-failure